### ISSUE TITLE
Yay you're the first person I see that has the right object structure

### ISSUE THREAD

**Issue by Razpudding** [pesh12/ENES-JS#15]
https://github.com/pesh12/Javascript1/blob/cc41a99136c5b32ff99305b8ad99c381651eccc5/Week3/allTogetger.js#L61

🏅

**Comment by ekocibar** [comment]
Thanks Laurens ! @Razpudding 
There is a Turkish proverb for people who are just in the beginning and has to work more and more 
it's like  << You have to eat all the breads from 40 bakeries >>
So I have to eat more and more

**Comment by pesh12** [comment]
💪💪
