### ISSUE TITLE
Your newlist function is really cool, here's how to make it better

### ISSUE THREAD

**Issue by Razpudding** [pesh12/ENES-JS#16]
https://github.com/pesh12/Javascript1/blob/cc41a99136c5b32ff99305b8ad99c381651eccc5/Week3/allTogetger.js#L123

So the function already works really well. I like how you add headings to each book.
First thing that could be better is adding the lis to a list. Theyre list elements after all so adding them to the body doesnt make sense, give them an ul parent.
Second: What could be better is the variable names. instead of item1 for instance, write liElement.
Third: Try giving the newlist a parameter, and have that parameter be the list of books. That way you could also pass it another list of books and it would still work!

**Comment by ekocibar** [comment]
Thanks again. 
Done.
