### ISSUE TITLE
Your solution for ass. 2 is correct but there is one weird line

### ISSUE THREAD

**Issue by Razpudding** [pesh12/ENES-JS#6]
https://github.com/pesh12/ENES-JS/blob/master/Week1/0%20allTogether.js#L20

Why are you passing an assignment of "a=" to the function? That' a bit confusing and unnecessary.

**Comment by ekocibar** [comment]
Yea I know it is weird.
I was trying whether it would work or not. 
Next time I will keep those with myself :)
