### ISSUE TITLE
Ass 4. is really well done! How did you come up with this solution?

### ISSUE THREAD

**Issue by Razpudding** [pesh12/ENES-JS#7]
Please describe below how you got this idea.

**Comment by ekocibar** [comment]
Create a function named vehicleType that receives a color, and a code, 1 for car, 2 for motorbike. And prints "a blue motorbike" for example when called as vehicleType("blue", 2)

I have done just what asked. 
first introduced a function that takes two parameters color and code
And placed the conditions with if/ else if statements:   for car(1) and motorbike(2)
